# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image_id', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
